---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include docker"
      include_role:
        name: "docker"
    - name: "Include http_checker"
      include_role:
        name: "http_checker"
